name: Build and Release
permissions:
  contents: write
  packages: write
on:
  push:
    tags:
      - "*"
jobs:
  build-and-release:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest]
    env:
      VCPKG_ROOT: ${{ github.workspace }}/vcpkg
      USERNAME: debugee
      VCPKG_EXE: ${{ github.workspace }}/vcpkg/vcpkg
      FEED_URL: https://nuget.pkg.github.com/debugee/index.json
      VCPKG_BINARY_SOURCES: "clear;nuget,https://nuget.pkg.github.com/debugee/index.json,readwrite"
    steps:
      - name: Checkout code
        uses: actions/checkout@v7

      - name: Get Tag name
        run: |
          TAG=${GITHUB_REF#refs/tags/}
          REPO_NAME=${GITHUB_REPOSITORY#*/}
          REPO_OWNER=${GITHUB_REPOSITORY%/*}
          echo "TAG=$TAG" >> $GITHUB_ENV
          echo "REPO_NAME=$REPO_NAME" >> $GITHUB_ENV
          echo "REPO_OWNER=$REPO_OWNER" >> $GITHUB_ENV

      - name: Calculate GitHub tarball SHA256
        run: |
          TAG=${{ env.TAG }}
          REPO_NAME=${{ env.REPO_NAME }}
          SHA=$(git archive \
            --format=tar.gz \
            --prefix="${REPO_NAME}-${TAG}/" \
            "$TAG" | shasum -a 256 | awk '{print $1}')
          echo "SHA=$SHA" >> $GITHUB_ENV

      - name: Configure
        run: |
          cmake -S . -B build -DCMAKE_BUILD_TYPE:STRING=Release

      - name: Package
        run: |
          cmake --build build --target package --config Release

      - name: Generate brew formula
        run: |
          cmake \
            -DGITHUB_OWNER=${{ env.REPO_OWNER }} \
            -DGITHUB_REPO=${{ env.REPO_NAME }} \
            -DTAG=${{ env.TAG }} \
            -DSOURCE_SHA256=${{ env.SHA }} \
            -P cmake/gen_brew_rb.cmake

      - name: Release
        uses: softprops/action-gh-release@v3
        if: startsWith(github.ref, 'refs/tags/')
        with:
          body: "mytool release"
          files: |
            build/*.zip
            build/*.rb